version: "3.6"
services:
  mail-service:
    build:
      context: ./micro-email/docker
    image: "laravelapp"
    ports:
      - 8000:80
    volumes:
      - ./micro-email/:/var/www/html

  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui


  websocket-service:
    build:
      context: ./micro-websocket/docker
    image: "laravelapp"
    ports:
      - 8800:80
    volumes:
      - ./micro-websocket:/var/www/html

  app:
    build:
      context: ./api/docker
    image: "laravelapp"
    ports:
      - '8080:8080'
    volumes:
      - './api/:/var/www/html'

  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: app
      #      # You should definitely change the password in production
      MYSQL_PASSWORD: ChangeMe
      MYSQL_USER: symfony
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - db-data:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
