vich_uploader:
    db_driver: orm

    mappings:
        media_object:
            uri_prefix: /
            upload_destination: '%kernel.project_dir%/public/media'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer
